drop table if exists book_comments;
drop table if exists books;
drop table if exists authors;
drop table if exists genres;

create table authors (
    id bigint generated by default as identity primary key,
    full_name varchar(255) not null
);

create table genres (
    id bigint generated by default as identity primary key,
    name varchar(255) not null
);

create table books (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    author_id bigint not null,
    genre_id bigint not null,
    constraint fk_books_authors foreign key (author_id) references authors(id),
    constraint fk_books_genres foreign key (genre_id) references genres(id)
);

create table book_comments (
    id bigint generated by default as identity primary key,
    text varchar(1000) not null,
    book_id bigint not null,
    constraint fk_book_comments_books foreign key (book_id) references books(id) on delete cascade
);